### ISSUE TITLE
Challenge #5 - Jupyter-based application for vertical cross-sections

### ISSUE THREAD

**Issue by jwagemann** [esowc/challenges_2019#5]
# Challenge 5
### Jupyter-based application for vertical cross-sections

Develop a Jupyter-based application to allow interactive selection, computation and display of atmospheric vertical cross sections through xarray data objects.

**Goal**: Create a useful interactive Jupyter-based application that display atmospheric vertical cross sections.

<br>

| | |
|------------|----------------------------------------------------------------------|
| **Mentors** | @iainrussell, @sk-ec  |
| **Skills required** | - Python programming  </br> - Jupyter notebook environment  </br>- Linux / MacOS X environment |
<hr>

#### What data/system(s) should be used?
The user environment would be Jupyter notebooks, and the data access/computation engine would be Metview. The plotting of the cross section itself would be done by Metview. The task would be to create a geographical line-selection widget and link it with Metview’s ability to compute and plot cross sections. This would all be within a Jupyter notebook. As Metview runs on Linux and Mac OS X, these are the supported platforms.
#### What is the current problem/limitation?
Users can create cross sections in Metview, but changing the line across which it is computed involves several steps before they can see the result. We’d like something where the user can change the line and instantly see the result in the plot. We would also like to allow multi-segment lines to be used, something which is not currently possible. Also, it would be really helpful to analysts to be able to see a field plotted on the map where they select their cross section line (e.g. so they can draw it through an area of interest). If we base this on xarray as input data then it could be used for NetCDF data as well as GRIB (Metview currently only handles GRIB for this task).
#### Possible idea for the implementation:
The line selection tool could be done with any technology available from Jupyter; Metview’s Python interface should be used for data access and for plotting the cross section. 

The picture below is what we currently have in Metview (standalone, not Jupyter) - the new solution should look something like this, but with a direct link between the two widgets.

![challenge5_image](https://user-images.githubusercontent.com/8168920/51268481-24960880-19b8-11e9-8ff7-bdbc954e5f3f.png)

**Comment by tibi77** [comment]
Hello! As you may see from my github I have some experience with python. What data should be displayed ? Or a better question should the project goal be creating a framework for interfacing Metview in Jupyter.
Also can I still apply if I do not have much experience with creating Jupyter widgets?

**Comment by jwagemann** [comment]
#### REMINDER: Deadline to register and submit your proposal is upcoming Sunday, 21 April at 23:59 GMT!
Application process is a 2-step process:
- You have to first register [here](https://events.ecmwf.int/event/117/registrations/47/), and then
- Submit a proposal under "Call for abstract" [here](https://events.ecmwf.int/event/117/abstracts/).

Applications without a submitted proposal will not be taken under consideration!
We are looking forward to your proposal!

**Comment by iainrussell** [comment]
Hi @tibi77,

The data comes from GRIB files - GRIB is one of the main formats used to store meteorological forecast data. Your code would not have to directly access this data format.

The simple version is that the first widget you create is something that displays a map and allows the user to select a line on it (users may want to zoom so they can select a precise area). They may also want to enter the co-ordinates of the lat/lon end-points of the line as text. The background map graphics could be generated by Metview (it can give you a PNG or SVG for example). So there's no data access there. It's mainly an exercise in Jupyter widgets.

Then, a call to a Metview function would take the end-points of this line, plus a path to the data file as input (or pass an xarray object), and Metview could return a PNG file that could be displayed in the second widget.

Each time the line is modified in the first widget, this last step would be repeated so that the plot is updated automatically.

The extended version of this is that the line-selection widget would also be able to display some data on the map. This would be done by again calling a Metview function to produce a PNG (or SVG) file that could be used as a background to the widget.

I hope this helps a little bit!

Iain
